### ISSUE TITLE
ModuleNotFoundError: No module named 'bidi.algorithm'

### ISSUE THREAD

**Issue by franciscoabenza** [Ag2S1/Sibyl-System#5]
```
2024-07-22 20:13:15,444 WARNING services.py:2009 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 67100672 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=1.57gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2024-07-22 20:13:16,597 INFO worker.py:1749 -- Started a local Ray instance.
Traceback (most recent call last):
  File "/workspaces/Sibyl-System/main.py", line 29, in <module>
    from utils.browser_utils import SimpleTextBrowser
  File "/workspaces/Sibyl-System/utils/browser_utils.py", line 19, in <module>
    from .mdconvert import MarkdownConverter, UnsupportedFormatException, FileConversionException
  File "/workspaces/Sibyl-System/utils/mdconvert.py", line 30, in <module>
    import easyocr
  File "/home/codespace/.local/lib/python3.10/site-packages/easyocr/__init__.py", line 1, in <module>
    from .easyocr import Reader
  File "/home/codespace/.local/lib/python3.10/site-packages/easyocr/easyocr.py", line 9, in <module>
    from bidi.algorithm import get_display
ModuleNotFoundError: No module named 'bidi.algorithm'
```

**Comment by Ag2S1** [comment]
Have you tried ```pip install -r requirements.txt```?

**Comment by franciscoabenza** [comment]
Yes, of course
